name: practicing some CI/CD with github actions

on:
  workflow_dispatch:
jobs:
  deployement:
    runs-on: ubuntu-latest

    environment:
      name: production
      url: https://github.com

    steps:
      - name: 'Print secret from the environment'
        run: |
          echo "APP_SECRET: ${{ secrets.APP_SECRET }}"
